/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as EntrepriseRouteImport } from './routes/entreprise'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as TalentTableauDeBordRouteImport } from './routes/talent-tableau-de-bord'
import { Route as ProfilIdRouteImport } from './routes/profil.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseRoute = EntrepriseRouteImport.update({
  id: '/entreprise',
  path: '/entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentTableauDeBordRoute = TalentTableauDeBordRouteImport.update({
  id: '/talent-tableau-de-bord',
  path: '/talent-tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIdRoute = ProfilIdRouteImport.update({
  id: '/profil/$id',
  path: '/profil/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/entreprise': typeof EntrepriseRoute
  '/inscription': typeof InscriptionRoute
  '/kids': typeof KidsRoute
  '/parcours': typeof ParcoursRoute
  '/recherche': typeof RechercheRoute
  '/talent': typeof TalentRoute
  '/talent-tableau-de-bord': typeof TalentTableauDeBordRoute
  '/profil/$id': typeof ProfilIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/entreprise': typeof EntrepriseRoute
  '/inscription': typeof InscriptionRoute
  '/kids': typeof KidsRoute
  '/parcours': typeof ParcoursRoute
  '/recherche': typeof RechercheRoute
  '/talent': typeof TalentRoute
  '/talent-tableau-de-bord': typeof TalentTableauDeBordRoute
  '/profil/$id': typeof ProfilIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/entreprise': typeof EntrepriseRoute
  '/inscription': typeof InscriptionRoute
  '/kids': typeof KidsRoute
  '/parcours': typeof ParcoursRoute
  '/recherche': typeof RechercheRoute
  '/talent': typeof TalentRoute
  '/talent-tableau-de-bord': typeof TalentTableauDeBordRoute
  '/profil/$id': typeof ProfilIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/entreprise'
    | '/inscription'
    | '/kids'
    | '/parcours'
    | '/recherche'
    | '/talent'
    | '/talent-tableau-de-bord'
    | '/profil/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/entreprise'
    | '/inscription'
    | '/kids'
    | '/parcours'
    | '/recherche'
    | '/talent'
    | '/talent-tableau-de-bord'
    | '/profil/$id'
  id:
    | '__root__'
    | '/'
    | '/connexion'
    | '/entreprise'
    | '/inscription'
    | '/kids'
    | '/parcours'
    | '/recherche'
    | '/talent'
    | '/talent-tableau-de-bord'
    | '/profil/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnexionRoute: typeof ConnexionRoute
  EntrepriseRoute: typeof EntrepriseRoute
  InscriptionRoute: typeof InscriptionRoute
  KidsRoute: typeof KidsRoute
  ParcoursRoute: typeof ParcoursRoute
  RechercheRoute: typeof RechercheRoute
  TalentRoute: typeof TalentRoute
  TalentTableauDeBordRoute: typeof TalentTableauDeBordRoute
  ProfilIdRoute: typeof ProfilIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise': {
      id: '/entreprise'
      path: '/entreprise'
      fullPath: '/entreprise'
      preLoaderRoute: typeof EntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-tableau-de-bord': {
      id: '/talent-tableau-de-bord'
      path: '/talent-tableau-de-bord'
      fullPath: '/talent-tableau-de-bord'
      preLoaderRoute: typeof TalentTableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/$id': {
      id: '/profil/$id'
      path: '/profil/$id'
      fullPath: '/profil/$id'
      preLoaderRoute: typeof ProfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnexionRoute: ConnexionRoute,
  EntrepriseRoute: EntrepriseRoute,
  InscriptionRoute: InscriptionRoute,
  KidsRoute: KidsRoute,
  ParcoursRoute: ParcoursRoute,
  RechercheRoute: RechercheRoute,
  TalentRoute: TalentRoute,
  TalentTableauDeBordRoute: TalentTableauDeBordRoute,
  ProfilIdRoute: ProfilIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
